apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

configMapGenerator:
- name: envoy-proxy-cm
  files:
  - config/envoy.yaml

secretGenerator:
- name: envoy-proxy-tls
  files:
  - config/crt.pem
  - config/key.pem
