apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

configMapGenerator:
- name: haproxy-server-cm
  files:
  - config/haproxy.cfg

secretGenerator:
- name: haproxy-server-tls
  files:
  - config/haproxy.pem